FROM python:3.7

SHELL ["/bin/bash", "-c"]

RUN apt update && apt install -y cmake
RUN python3 -m venv app
RUN chmod +x app/bin/activate
RUN app/bin/activate
WORKDIR /app


COPY face_recognition/ .

RUN pip install --upgrade pip setuptools && \
    pip install -r requirements.txt

EXPOSE 5000

CMD ["uwsgi", "--http", "5000", "--wsgi-file", "api.py", "--callable", "app", "--process", "4", "--threads", "2"]

